### ISSUE TITLE
yaml_parse_file() does not allow other than alphanumeric characters in yaml

### ISSUE THREAD

**Issue by ghost** [GetSky/phalcon-config-loader#9]
Warning: yaml_parse_file(): scanning error encountered during parsing: found unexpected non-alphabetical character

This is related to "%" character used for placeholders.

**Comment by GetSky** [comment]
Currently use: '%res%'
See: https://github.com/JimmDiGrizli/pherlin/commit/7bd5d1e4c63cd09df0caad4d72af25ed00c5e97a
